services:
  app:
    image: ghcr.io/yxtay/agentic-recommenders:main
    build:
      cache_from:
        - ghcr.io/yxtay/agentic-recommenders:cache
        - ghcr.io/yxtay/agentic-recommenders:main
    volumes:
      - ./data:/work/app/data
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
